"""create initial tables

Revision ID: b0a006fa1779
Revises: 
Create Date: 2025-08-16 17:38:18.446247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a006fa1779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brand_name', 'brands', ['name'], unique=False)
    op.create_index(op.f('ix_brands_created_at'), 'brands', ['created_at'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_index(op.f('ix_brands_website_url'), 'brands', ['website_url'], unique=True)
    op.create_table('competitor_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('competitor_brand_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'competitor_brand_id', name='uq_competitor_pair')
    )
    op.create_index(op.f('ix_competitor_map_brand_id'), 'competitor_map', ['brand_id'], unique=False)
    op.create_index(op.f('ix_competitor_map_competitor_brand_id'), 'competitor_map', ['competitor_brand_id'], unique=False)
    op.create_index(op.f('ix_competitor_map_created_at'), 'competitor_map', ['created_at'], unique=False)
    op.create_table('contact_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'PHONE', name='contacttype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_details_brand_id'), 'contact_details', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contact_details_created_at'), 'contact_details', ['created_at'], unique=False)
    op.create_index('ix_contact_type', 'contact_details', ['type'], unique=False)
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_brand_id'), 'crawl_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_crawl_logs_created_at'), 'crawl_logs', ['created_at'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=191), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_faq_question', 'faqs', ['question'], unique=False)
    op.create_index(op.f('ix_faqs_brand_id'), 'faqs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_faqs_created_at'), 'faqs', ['created_at'], unique=False)
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=False)
    op.create_table('important_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('ORDER_TRACKING', 'CONTACT_US', 'BLOG', 'FAQ', 'ABOUT', 'HOMEPAGE', 'OTHER', name='linktype'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'link_type', name='uq_link_brand_type')
    )
    op.create_index(op.f('ix_important_links_brand_id'), 'important_links', ['brand_id'], unique=False)
    op.create_index(op.f('ix_important_links_created_at'), 'important_links', ['created_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVACY', 'REFUND', 'RETURN', 'SHIPPING', 'TERMS', name='policytype'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'type', name='uq_policy_brand_type')
    )
    op.create_index(op.f('ix_policies_brand_id'), 'policies', ['brand_id'], unique=False)
    op.create_index(op.f('ix_policies_created_at'), 'policies', ['created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_hero', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'handle', name='uq_product_brand_handle')
    )
    op.create_index('ix_product_is_hero', 'products', ['is_hero'], unique=False)
    op.create_index('ix_product_title', 'products', ['title'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_shopify_product_id'), 'products', ['shopify_product_id'], unique=False)
    op.create_table('social_handles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER', 'YOUTUBE', 'PINTEREST', 'LINKEDIN', 'OTHER', name='socialplatform'), nullable=False),
    sa.Column('handle_or_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'platform', name='uq_social_brand_platform')
    )
    op.create_index(op.f('ix_social_handles_brand_id'), 'social_handles', ['brand_id'], unique=False)
    op.create_index(op.f('ix_social_handles_created_at'), 'social_handles', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_handles_created_at'), table_name='social_handles')
    op.drop_index(op.f('ix_social_handles_brand_id'), table_name='social_handles')
    op.drop_table('social_handles')
    op.drop_index(op.f('ix_products_shopify_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index('ix_product_title', table_name='products')
    op.drop_index('ix_product_is_hero', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_policies_created_at'), table_name='policies')
    op.drop_index(op.f('ix_policies_brand_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_important_links_created_at'), table_name='important_links')
    op.drop_index(op.f('ix_important_links_brand_id'), table_name='important_links')
    op.drop_table('important_links')
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_created_at'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_brand_id'), table_name='faqs')
    op.drop_index('ix_faq_question', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_crawl_logs_created_at'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_brand_id'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    op.drop_index('ix_contact_type', table_name='contact_details')
    op.drop_index(op.f('ix_contact_details_created_at'), table_name='contact_details')
    op.drop_index(op.f('ix_contact_details_brand_id'), table_name='contact_details')
    op.drop_table('contact_details')
    op.drop_index(op.f('ix_competitor_map_created_at'), table_name='competitor_map')
    op.drop_index(op.f('ix_competitor_map_competitor_brand_id'), table_name='competitor_map')
    op.drop_index(op.f('ix_competitor_map_brand_id'), table_name='competitor_map')
    op.drop_table('competitor_map')
    op.drop_index(op.f('ix_brands_website_url'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_created_at'), table_name='brands')
    op.drop_index('ix_brand_name', table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
